name: Automated Tests

on: pull_request

jobs:
  jest:
    name: Jest Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/iron"

      - run: npm ci

      # Definir as variáveis de ambiente do SMTP
      - name: Set up SMTP environment variables
        run: |
          echo "SMTP_HOST=${{ secrets.SMTP_HOST }}" >> $GITHUB_ENV
          echo "SMTP_PORT=${{ secrets.SMTP_PORT }}" >> $GITHUB_ENV
          echo "SMTP_USER=${{ secrets.SMTP_USER }}" >> $GITHUB_ENV
          echo "SMTP_PASS=${{ secrets.SMTP_PASS }}" >> $GITHUB_ENV
          echo "TO_EMAIL=${{ secrets.TO_EMAIL }}" >> $GITHUB_ENV

      - run: npm test
